import {api} from './api';
import {ContactCustomVariable} from '../interfaces/ContactCustomVariable';

export type CreateCustomVarPayload = Omit<ContactCustomVariable, 'uuid' | 'created_at' | 'updated_at' | 'key'> & {
    key: string; // keep – user may override autogenerated one
};

export async function getCustomVariables(): Promise<ContactCustomVariable[]> {
    const {data} = await api.get<{ data: ContactCustomVariable[] }>('/contact-custom-variables');
    return data.data;
}

export async function createCustomVariable(payload: CreateCustomVarPayload) {
    const {data} = await api.post<{ data: ContactCustomVariable }>('/contact-custom-variables', payload);
    return data.data;
}

export async function updateCustomVariable(uuid: string, payload: Partial<CreateCustomVarPayload>) {
    const {data} = await api.post<{ data: ContactCustomVariable }>(`/contact-custom-variables/${uuid}`, payload);
    return data.data;
}

export async function deleteCustomVariable(uuid: string) {
    await api.delete(`/contact-custom-variables/${uuid}`);
}
